# ! definition order matters
# keep this order if you want systemctl daemon-reload
# before anything else in case of multiple notify
- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: restart docker
  service:
    name: docker
    state: restarted
